### ISSUE TITLE
Improvement of image size.

### ISSUE THREAD

**Issue by MGriot** [Acylation/obsidian-chem#14]
### What would you like to be added?

It would be nice if you could choose the standard size of the bonds. Let me explain better, the plugin is fantastic but I find the image size option inconvenient. It doesn’t adapt well for all molecules, especially if they have different sizes. It would be more useful to be able to choose the standard size of bonds or atoms, in this way all molecules would be on the same scale. I imagine that as a request it is complicated but it would be nice to have this function. 
Maybe you could directly insert the choice of the image size and whether to standardize the size of the bonds and atoms in the codeblock, in order to make it more adaptive.

### Why is this needed?

This would allow for better integration into obsidian notes by avoiding having very small molecules that are impossible to read if they are too large

**Comment by Acylation** [comment]
I did some experiment and found that this could be easily solved by changing default 'scale' option from zero to a value, rather than explicit assign imgWidth.

![image](https://github.com/Acylation/obsidian-chem/assets/73122375/b1671b6a-1d05-439a-b914-07ab25f14bc4)

However, as shown in the screenshot, there are some typography problems need to be solved. I'll try to use table element to format this.

Another problem is, the structures are now rendered in png format, this would lead to low resolutions. Chaning to svg may be helpful.

<img width="583" alt="image" src="https://github.com/Acylation/obsidian-chem/assets/73122375/8cbc5f44-9a87-43bc-95d7-8193d01dec24">
